### ISSUE TITLE
越界回弹问题

### ISSUE THREAD

**Issue by Equalzys** [shichaohui/gesture_zoom_box#3]
// 处理 Y 轴边界 请使用这个，下边注释的代码会导致放大后不能滑动到边界
      double scaleOffsetY = context.size.height * (realScale - 1.0) / 2;
//      double scaleOffsetY =
//          (context.size.height * realScale - MediaQuery.of(context).size.height) / 2;

**Comment by shichaohui** [comment]
边界是相对于屏幕的，不是相对于图片自身，所以不需要修改。
